#These words are generated by Manual With chatGPT and I added my own words

import sqlite3;
import re
from pathlib import Path

PositiveWordsDutch = [
	"aangenaam",
	"bewonderenswaardig",
	"bemoedigend",
	"best",
	"briljant",
	"buitengewoon",
	"complimenten",
	"fantastisch",
	"fijn",
	"geweldig",
	"gelukkig",
	"genieten",
	"goed",
	"hoopvol",
	"inspirerend",
	"leuk",
	"lief",
	"magnifiek",
	"mooi",
	"positief",
	"prachtig",
	"sterk",
	"succes",
	"trots",
	"uitmuntend",
	"verheugd",
	"verrukkelijk",
	"vertrouwen",
	"vriendelijk",
	"waarderen",
	"wenselijk",
	"wonderbaarlijk",
	"zegen",
	"zonnig",
	"aanlokkelijk",
	"aanmoedigend",
	"aantrekkelijk",
	"adembenemend",
	"fantasierijk",
	"gezellig",
	"harmonieus",
	"hoopgevend",
	"inspirerend",
	"vernieuwend",
	"verrijkend",
	"vrolijk",
	"waardevol",
	"weelderig",
	"welwillend",
	"wonderlijk",
	"zalig",
	"zorgeloos",
]
NegativeWordsDutch = [
    "klein"
	"afschuwelijk",
	"bedroevend",
	"beklagenswaardig",
	"bitter",
	"deprimerend",
	"ellendig",
	"frustrerend",
	"gemeen",
	"gruwelijk",
	"hatelijk",
	"hekel",
	"jammerlijk",
	"lelijk",
	"miserabel",
	"negatief",
	"onaangenaam",
	"onprettig",
	"onuitstaanbaar",
	"teleurstellend",
	"treurig",
	"vervelend",
	"verwerpelijk",
	"weerzinwekkend",
	"zuur",
	"afkeer",
	"boos",
	"chagrijnig",
	"dom",
	"dreigend",
	"duister",
	"droevig",
	"frustratie",
	"gewelddadig",
	"grimmig",
	"haat",
	"onbevredigend",
	"onplezierig",
	"ontmoedigend",
	"ontstemd",
	"onzeker",
	"pijnlijk",
	"probleem",
	"teleurstelling",
	"treurnis",
	"verdrietig",
	"verstoord",
	"verveling",
	"zorgwekkend",
	"afgrijselijk",
	"benauwend",
	"bezorgdheid",
	"bitterheid",
	"deceptie",
	"desillusie",
	"eenzaam",
	"ellende",
	"falen",
	"futloos",
	"geïrriteerd",
	"gestrest",
	"gloomy",
	"grimmigheid",
	"hartzeer",
	"hekel",
	"hoopeloos",
	"ijskoud",
	"irritatie",
	"kwelling",
	"leed",
	"melancholie",
	"misère",
	"mislukking",
	"neerslachtig",
	"onbevredigend",
	"ontevreden",
	"onveilig",
	"onzekerheid",
	"overwhelmed",
	"pessimisme",
	"probleem",
	"rampzalig",
	"rancuneus",
	"rouw",
	"somberte",
	"spijt",
	"teleurstelling",
	"teneergeslagen",
	"triest",
	"verdriet",
	"verlegen",
	"verlies",
	"vermoeiend",
	"vernieling",
	"verontrustend",
	"verslagen",
	"verwoestend",
	"verwrongen",
	"verwonding",
	"verwarring",
	"woede",
	"woedend"
]

connection = sqlite3.connect('database.db')
cursor = connection.cursor()
cursor.execute('DROP TABLE IF EXISTS reviewAnalyzeResults')
cursor.execute('CREATE TABLE reviewAnalyzeResults (id INTEGER PRIMARY KEY, content TEXT, opinion TEXT)')


txt = Path('demofile2.txt').read_text()


# use regex to find the text field and extract the text inside ""
text_matches = re.findall(r'"text":"(.*?)"', txt)

# print the extracted text
for match in text_matches:
    if any(word in match for word in PositiveWordsDutch):
        sentiment = "Positive"
    elif any(word in match for word in NegativeWordsDutch):
        sentiment = "Negatief"
    else:
        sentiment = "Neutral"

    # Insert the result into the database
    cursor.execute("INSERT INTO reviewAnalyzeResults (content, opinion) VALUES (?, ?)", (match, sentiment))

# Commit the transaction
connection.commit()

# Close the connection
connection.close()